moodlehq/moodle-local_codechecker

- moodle/Sniffs/Commenting/InlineCommentSniff.php
- moodle/tests/fixtures/moodle_comenting_inlinecomment.php
- moodle/tests/moodlestandard_test.php
When some inline phpdoc is found, it's verified if
it's being used to define the variable type used
in the next line of code. If next line of code
does not match, an error is returned (TypeHintingMatch).
> CONTRIB-6025 phpdoc: Allow type-hinting

- moodle/Sniffs/Commenting/InlineCommentSniff.php
- moodle/tests/fixtures/moodle_comenting_inlinecomment.php
- moodle/tests/moodlestandard_test.php
Now @var phpdoc blocks are also allowed if next line is a list()
statement with any of the variables being the documented one.
> CONTRIB-6025 phpdoc: Allow type-hinting for list() assignments

- CHANGES.md
- moodle/Sniffs/Strings/ForbiddenStringsSniff.php
- moodle/tests/fixtures/moodle_strings_forbiddenstrings.php
- moodle/tests/moodlestandard_test.php
Not much to say. It looks for `$string['xxxxxx(_desc|_help)` to allow the backticks.
Already installed in the laptop, it's covered with tests and seems to be working (can try it against `lang/en/plugin.php`, previously failing).
Ciao :-)
> MDLSITE-4197 backticks: Allow them in lang strings (valid Markdown)

- CHANGES.md
- moodle/tests/fixtures/generic_whitespace_scopeindent.php
- pear/PHP/CodeSniffer.php
- pear/PHP/CodeSniffer/CLI.php
- pear/PHP/CodeSniffer/File.php
- pear/PHP/CodeSniffer/Fixer.php
- pear/PHP/CodeSniffer/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- pear/PHP/CodeSniffer/Standards/Generic/Sniffs/Functions/CallTimePassByReferenceSniff.php
- pear/PHP/CodeSniffer/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
- pear/PHP/CodeSniffer/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- pear/PHP/CodeSniffer/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- pear/PHP/CodeSniffer/Standards/PSR2/ruleset.xml
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/InlineIfDeclarationSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/PHP/InnerFunctionsSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- pear/PHP/CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- pear/PHP/CodeSniffer/Tokenizers/PHP.php
- pear/PHP/CodeSniffer/Tokens.php
- pear/PHP/README.md
- readme_moodle.txt
Just upgraded to PHP_CodeSniffer 2.6.2 dev (2d3a4a8) and added some fixtures to ensure they are not reported as errors anymore.
Also, I've run it about various of the reported [cases in the tracker](https://tracker.moodle.org/browse/CONTRIB-6206) and, unless I'm missing something, all them seems fixed with the patch applied.
> Indentation problems

- moodle/Sniffs/NamingConventions/ValidVariableNameSniff.php
See https://github.com/moodlerooms/moodle-plugin-ci/issues/24
> http_response_header should be allowed

- .travis.yml
- PHP 3.2 and up get 5.6 and 7.0
- PHP 3.0 and 3.1 get 5.4 and 7.0
- PHP < 3.0 get php 5.4 only
> NOBUG: Adjust php combinations to, always, check older and newer

- moodle/Sniffs/NamingConventions/ValidFunctionNameSniff.php
This method is part of the PHPUnit API and it should not throw the
letter case error.
Discussed at https://github.com/moodlerooms/moodle-plugin-ci/issues/26
> Allow setUpBeforeClass as a valid function name

- .travis.yml
They will be executed with php 5.6 and 7.0
> NOBUG: Add MOODLE_32_STABLE runs

- moodle/Sniffs/Files/RequireLoginSniff.php
- moodle/tests/fixtures/moodle_files_requirelogin/admin_externalpage_setup_ok.php
- moodle/tests/fixtures/moodle_files_requirelogin/cliscript_ok.php
- moodle/tests/fixtures/moodle_files_requirelogin/nomoodlecookies_ok.php
- moodle/tests/fixtures/moodle_files_requirelogin/problem.php
- moodle/tests/fixtures/moodle_files_requirelogin/require_course_login_ok.php
- moodle/tests/fixtures/moodle_files_requirelogin/require_login_ok.php
- moodle/tests/moodlestandard_test.php
Sniff to detect files without required login functions, based on the ideas from @FMCorz in [MDLSITE-3688](https://tracker.moodle.org/browse/MDLSITE-3688).
I am torn about this idea - I am not sure if we can do this sniff reliably and thats probably the most important blocker. I'm especially worried about the use case of a module which makes its own wrapper function doing these kind of checks. This would seem noisy - we have an example of that in useredit_setup_preference_page().
On the other hand, I think this could potentially find real important issues in files. So maybe it would be useful as a warning. Interested in your thoughts @mudrd8mz and @mrmark.
Current matches in core isn't too bad
https://gist.github.com/danpoltawski/edc6b9ae1b6ccb62482be93a3c2052b7
> MDLSITE-3688 login checks sniff

- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/tests/fixtures/moodle_files_moodleinternal/warning.php
- moodle/tests/moodlestandard_test.php
Borrowed heavily from
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
We turn the warning into an error if side effect detected in the code.
Perhaps we should use different terminology in the errors/warnings? Thoughts welcome. Also needs some better testing
> MDLSITE-3688 error if side effect detected

- .travis.yml
- tests/behat/ui.feature
Finally it has been done by:
1) Using the new steps (MDL-56614) for 31 and up.
2) Disable running behats for 30 and down (fair enough,
no UI changes are expected there and they have been
working ok. Plus all them are under security-only support
so...
> CONTRIB-6619 behat: make them pass for 32 and up

- moodle/ruleset.xml
- moodle/tests/fixtures/squiz_whitespace_operatorspacing.php
- moodle/tests/moodlestandard_test.php
If after an operator new line character is encountered, we should not generate warnings or notices.
> Consider new lines as valid characters after operators

- moodle/ruleset.xml
- moodle/tests/fixtures/squiz_whitespace_objectoperatorspacing.php
- moodle/tests/moodlestandard_test.php
The indentation sniff (PEAR.WhiteSpace.ObjectOperatorIndent) does
not cover all the cases, just the "object" (variable) ones, so I've
created and issue @ PHP_CodeSniffer about it:
https://github.com/squizlabs/PHP_CodeSniffer/issues/2009
> MDLSITE-2825 Allow obj-op at beginning + basic indentation checks

- .travis.yml
Here and there, more with other travis modes, the oracle java packages fail to download and install. We only need a JRE here, so switching to OpenJDK's one, that is ok enough for our needs.
> NOBUG: Switch to OpenJDK JRE, more stable packages

- README.md
The link to the bug tracker is broken. Use the link to the Moodle bug tracker from the official plugin site (https://moodle.org/plugins/view.php?plugin=local_codechecker). Also, note that the link to http://www.phpsrc.org/ (for the Eclipse plugin) doesn't work anymore.
> Update bug tracker link in README.md

- moodle/Sniffs/Commenting/InlineCommentSniff.php
- moodle/tests/fixtures/moodle_comenting_inlinecomment.js
- moodle/tests/moodlestandard_test.php
When you run codechecker on JS file (this is permitted), eslint configuration comments do not pass "Inline Comments" sniff.
Tracker URL: https://tracker.moodle.org/browse/MDLSITE-5908
> MDLSIT-5908: respect eslint configuration comments in JS files

- .travis.yml
So openjdk is available by default and postgres better defined as
service.
Trying how it goes...
> Move to use virtualized Travis infrastructure (xenial)

- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/tests/fixtures/moodle_files_moodleinternal/nowarning.php
- moodle/tests/moodlestandard_test.php
Decided @ https://tracker.moodle.org/browse/MDLSITE-5967 files
with only one artifact (class, interface, trait) now don't
require the MOODLE_INTERNAL check anymore (although it continues
being allowed).
Only if the file has more than 1 artifact, the warning is emited.
Errors are emited when the file has side effects (global scope code). No change there.
> MDLSITE-6093 Mono-artifact files can be MOODLE_INTERNAL free

- pear/PHP/CodeSniffer/CLI.php
One of the multiple changes added by #65 towards php74 compatibility
was wrong and, without noticing it, we broke all the CLI short options
```
phpcs [-nwlsaepqvi]
```
Normally we don't use them, so it was unnoticed. Just today I was
doing some tests using the -s option (to show information about
the Sniffs detecting some errors) and I was, surprisingly, getting:
ERROR: option "-s" not known.
And the very same with every other short option.
So, this, just fixes this change, that was clearly wrong:
https://github.com/moodlehq/moodle-local_codechecker/commit/04810acd95b734543c6af6b247e715f2060dbd53#diff-857386c2703704c8ccc54229f7861931L453-R453
keeping a correct [0] there. To verify it:
- Run: pear/PHP/scripts/phpcs -i
- Current (broken) status: ERROR: option "-i" not known.
- With the …
> Allow short-options to work again (they were recently broken)

- moodle/ruleset.xml
- moodle/tests/moodlestandard_test.php
That way behavior will be always the same, irrespectively
of the client (codechecker, lang server, IDE, CLI...) and
only PHP file will be inspected.
Source: https://tracker.moodle.org/browse/CONTRIB-6175
To verify that the switch works, you can execute:
```
local/codechecker/pear/PHP/scripts/phpcs --standard=local/codechecker/moodle mod/forum/amd/src -v
```
- Before the patch: The .js files were inspected and a number of errors were reported.
- After the patch: No .js file is inspected anymore.
> Enforce, from the standard, that only PHP files will be ever handled.

- .travis.yml
- CHANGES.md
- pear/PHP/CodeSniffer.php
These escaped #65 and just noticed them today when executing
the bundled pear/PHP/scripts/phpcs binary (not reproducible
from web or tests).
Also fix an unrelated typo in CHANGES.md
Finally, have added some important changes to travis, aiming for simplicity (include jobs instead of matrix + excludes), better nodejs handling...
> php74: Fix a couple of remaining curly-bracket uses

- index.php
- run.php
While @ https://tracker.moodle.org/browse/CONTRIB-6175 we
defined at standard level that only php files should be ever
processed, it seems that only the "phpcs" binary observes that
setting.
Both the custom run.php script and the moodle plugin (UI) are
not informed of this so they continue processing other files.
This commit just ensures they stop doing that and, from now on
only PHP files will be processed.
> CONTRIB-8122 Stop processing non-php files (runner and UI)

- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/Sniffs/NamingConventions/ValidVariableNameSniff.php
Not much to say. In phpcs these are optional, but in phpcs3 they are mandatory. And also they help to find stuff easily when reported. So better have the detail ready for whenever migrating to phpcs3.
> Add a hand of missing codes that are mandatory in phpcs3

- moodle/tests/fixtures/moodle_files_moodleinternal/old_style_if_die_ok.php
MDL-69238 finally removes lib/coursecatlib.php so might as well remove any inclusion of this file in the local_codechecker plugin (even if the only inclusion of this file is in a fixture file that doesn't really end up including any file).
> Remove require of now-deleted coursecatlib.php

- .travis.yml
(part of https://tracker.moodle.org/browse/MDL-67415)
> Add support for 310 branch

- index.php
- lang/en/local_codechecker.php
- locallib.php
- tests/behat/ui.feature
Here's a simple change that lets you paste in a list of files to the textarea. It's super useful if checking files manually, because you can just do 'git show --name-only' on your commit, and then paste in the list of files to check.
I also increased the time limit to 600 because checking is so slow nowadays (which actually, is why it's often more useful to check a list of files rather than a whole folder at once - although often you also want to check files from multiple folders).
> Allow a list of files to be checked

- index.php
They were leading to the whole codebase being checked since #83.
> Avoid processing blank/empty paths

- README.md
More info available @ https://tracker.moodle.org/browse/MDLSITE-6246
Note the [repo has been already migrated](https://travis-ci.com/github/moodlehq/moodle-local_codechecker), this just updates references to the new one.
> Migrate from travis-ci.org to travis-ci.com

- locallib.php
The constants PHPCS_DEFAULT_ERROR_SEV and PHPCS_DEFAULT_WARN_SEV were defined in Codesniffer.php file, removed in phpcs3.
They are not used anymore in phpcs3, but they are still being used in locallib.php. We can change the constants to the default int value for errors and warnings severity level (5) but my personal take is that the code is easier to understand if we keep the constants.
> Add constants for default severity levels of warnings and errors

- moodle/Sniffs/Files/BoilerplateCommentSniff.php
- moodle/tests/fixtures/moodle_files_boilerplate/gnu_http.php
- moodle/tests/fixtures/moodle_files_boilerplate/gnu_https.php
- moodle/tests/moodlestandard_test.php
As per https://www.gnu.org/licenses/gpl-faq.en.html the recommended text is
```
You should have received a copy of the GNU General Public License along with this program;
if not, see <https://www.gnu.org/licenses>.
```
and the plugin skeleton generator is using this https URL now when generating boilerplates. As noticed by @adpe in https://github.com/mudrd8mz/moodle-tool_pluginskel/commit/d57c890cbb6f1180aa82c88cf340142b71f18573#commitcomment-43416888 this is raising false failure in moodle-plugin-ci.
The patch makes the boilerplace check tolerant to having `https://` in all `http://` links in the boilerplate.
> Allow www.gnu.org be referred to via https protocol in the boilerplate

- phpcs/autoload.php
- phpcs/package.xml
- phpcs/src/Config.php
- phpcs/src/Files/File.php
- phpcs/src/Fixer.php
- phpcs/src/Standards/Generic/Sniffs/CodeAnalysis/UnconditionalIfStatementSniff.php
- phpcs/src/Standards/PSR12/Sniffs/ControlStructures/BooleanOperatorPlacementSniff.php
- phpcs/src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc
- phpcs/src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc.fixed
- phpcs/src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc
- phpcs/src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc.fixed
- phpcs/src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- phpcs/src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- phpcs/src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
- phpcs/src/Tokenizers/PHP.php
- phpcs/src/Tokenizers/Tokenizer.php
- readme_moodle.txt
(see readme_moodle.txt for complete instructions)
Fixed the issue with get_declared_classes() behaviour change in PHP 7.4.
> Bumps phpcs to 3.5.8

- .travis.yml
- tests/local_codechecker_testcase.php
Has a TODO to remove the conditional code once Moodle 3.5 (that is
the only branch using PHPUnit 6) becomes 100% out of support.
Because of the :void return types... PHP 7.0 is left out, as far
as it doesn't support them.
Note that this change is already in the phpcs3 branch, so maybe it
will conflict on next rebase (or maybe no) :-)
> PHPUnit 8 compatibility, keeping PHPUnit 6 working for old branches

- classes/runner.php
- run.php
The run.php file has been reviewed and adapted to use the new runner class.
Some changes have been done to this runner class to add some of the config settings and also to get the interactive mode working ($this->processFile($file) is the method doing the magic and the exception has been added too to exit when 'q' key is pressed).
The following code has been removed to avoid to repeat some information:
`$reporter->cacheFileReport($file, $this->config);
`
The run.php file can be tested using the following commands:
- php run.php -h : Should display the help information
- php run.php local: Should run the codechecker over the moodle/local folder. Currently, it should return a couple of warnings in locallib.php file
- php run.php -i local: Should run the codechecker using the interactive …
> Adapt run.php to the new phpcs3 API

- index.php
There is no apparent reason to lock the session while processing the files, as no data needs to be persisted back to the session.
> Unlock the session before processing files

- CHANGES.md
- version.php
Maturity set from beta to stable.
> Bump to 2020110200 (v3.0.0) - Welcome phpcs 3

- .github/workflows/ci.yml
- .travis.yml
- locallib.php
Also, fix a couple of warnings to allow checks to pass and
enable a check that was previously commented out in
travis awaiting us to have a new moodle-plugin-ci version
now released.
> Add Github Actions to local_codechecker

- moodle/Sniffs/NamingConventions/ValidFunctionNameSniff.php
Fixing issue: https://github.com/moodlehq/moodle-local_codechecker/issues/117
> Add jsonSerialize as valid method name

- .travis.yml
With current pull limits @ dockerhub, it's possible to get failed
jobs just running 2-3 builds (each one having a good number of jobs).
With this patch, if both DOCKER_USER and DOCKER_TOKEN are defined
as environmental variables, they will be used to perform a login
to dockerhub, getting rid of pull limits.
> Login in dockerhub when possible to avoid pull limits

- README.md
Documentation related to PHP CS in moodle.org has been improved and a section to Visual Studio Code has been added to the README file of this project (it was requested in https://github.com/moodlehq/moodle-local_codechecker/issues/102 by Michael Milette).
> Add VSCode reference to README

- lang/en/local_codechecker.php
- run.php
Hi @stronk7 
Over the GUI it was implemented (https://tracker.moodle.org/browse/CONTRIB-3582), but no for CLI usage.
I've just made basics test usage due this small changes. But it works for my use case.
HTH
Adrian
> Pass excluded directories/files as CLI option

- moodle/ruleset.xml
- moodle/tests/fixtures/psr2_methods_methoddeclaration.php
- moodle/tests/moodlestandard_test.php
- tests/behat/ui.feature
Not defined by moodle coding standard, hence not contradicting it,
let's apply fallback to PSR-12:
https://www.php-fig.org/psr/psr-12/#46-abstract-final-and-static
Using the PSR-12 Sniff and covered by tests.
Fixes #138
> Apply for standard abstract/final/static positioning

- moodle/Sniffs/PHP/DeprecatedFunctionsSniff.php
- moodle/Sniffs/PHP/ForbiddenFunctionsSniff.php
- moodle/ruleset.xml
- moodle/tests/fixtures/moodle_php_deprecatedfunctions.php
- moodle/tests/moodlestandard_test.php
- tests/local_codechecker_testcase.php
This comes with 2 commits, first one slightly modifying/modernizing our `ForbiddenFunctions` Sniff, adding also some comments bout why we are using it.
And then a second commit where our new `DeprecatedFunctions` is introduced, really similar to the `ForbiddenFunctions` one, able to detect both PHP own deprecated functions and our ones, with alternatives where available.
Note that we have had to implement the `DeprecatedFunctions->addError()` method because the `Generic.DeprecatedFunctions` one is missing support to show the alternatives. I've created https://github.com/squizlabs/PHP_CodeSniffer/pull/3295 about that. If accepted upstream, we'll be able to remove that implementation from our Sniff.
Covered with tests (that hopefully will be all green soon) and implements #137.
Ciao :-)
> Forbidden and deprecated functions

- .github/workflows/ci.yml
- .travis.yml
- moodle/Sniffs/Commenting/InlineCommentSniff.php
- moodle/tests/fixtures/moodle_comenting_inlinecomment.php
- moodle/tests/moodlestandard_test.php
- tests/behat/ui.feature
- tests/coverage.php
This includes 2 commits:
1. Add the `coverage.php` file for the plugin, so when running with coverage enabled we get info about the files we are interested (keeping apart things like PHPCompatibilty, PHP_CodeSniffer... that are not ours).
2. Add a new sniff that supports the "return new class extends..." anonymous classes.
Important note: This will be failing a number of the checks, because `moodle-plugin-ci` ( that is in charge of checking this) still doesn't know about the new `moodlecheck` and `codechecker` improvements, namely:
- codechecker: Will fail with error in this patch line 19, because it's not aware of the new "return new class extends..." sniff that will allow those phpdoc blocks to exist.
- moodlecheck: Will fail because it's not aware that now we can skip the file phpdoc …
> Add coverage info (and related Sniff)

- .github/workflows/ci.yml
- .travis.yml
With core CI tests already passing for PHP 80 (see [the php80 epic](https://tracker.moodle.org/browse/MDL-70745) ), it's time to try it with codechecker.
So, bumping the highest runs of 311 and master from php74 to php80.
Let's see how it goes and if we need to perform any other change...
> Bump highest php version to 8.0 for 311 and master

- moodle/Sniffs/PHP/ForbiddenFunctionsSniff.php
The question about what function should be used instead of forbidden `error_log` is mentioned in discussion from time to time. This patch is specifying the most approriate replacement.
Related discussion in [MDL-58374](https://tracker.moodle.org/browse/MDL-58374?focusedCommentId=457672&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-457672).
> Specify alternative for error_log forbidden function.

- .github/workflows/ci.yml
New mariadb:10.6 makes the COMPRESSED row format read-only by default
because it's deprecated now and will be removed in mariadb:10.7
This is being tracked @ https://tracker.moodle.org/browse/MDL-72131
Once that issue is fixed and we switch to DYNAMIC or whichever the
final solution is, we'll unpin this.
> Make mariadb:10.5 sticky

- moodle/tests/moodlestandard_test.php
- tests/local_codechecker_testcase.php
Following the, more or less, de facto standard (MDL-71049) about
phpunit names and namespace, apply this small changes.
Also removing the file phpdoc block that is not needed any more.
Doing this change now before adding some new utilities and sniffs
that will require a better tests organization.
> Change test case name to match file and add namespace

- moodle/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- moodle/Sniffs/NamingConventions/ValidVariableNameSniff.php
- moodle/Sniffs/WhiteSpace/SpaceAfterCommaSniff.php
- moodle/tests/fixtures/moodle_namingconventions_variablename.php
- moodle/tests/fixtures/moodle_namingconventions_variablename.php.fixed
- tests/local_codechecker_testcase.php
For some simple sniffs, I think it makes sense to register them as fixable errors so phpcbf can automatically fix them. This patch introduces such fixes for:
- Variable names
- Method names
- Spaces between commas
> Introduce fixable errors for some sniffs

- moodle/Sniffs/PHPUnit/TestCaseNamesSniff.php
- moodle/tests/fixtures/phpunit/testcasenames_duplicate_exists.php
- moodle/tests/fixtures/phpunit/testcasenames_duplicate_proposed.php
- moodle/tests/fixtures/phpunit/testcasenames_exists_proposed.php
- moodle/tests/fixtures/phpunit/testcasenames_missing.php
- moodle/tests/fixtures/phpunit/testcasenames_missing_ns.php
- moodle/tests/fixtures/phpunit/testcasenames_nomatch.php
- moodle/tests/fixtures/phpunit/testcasenames_proposed_exists.php
- moodle/tests/fixtures/phpunit/testcasenames_test_testcase_irregular.php
- moodle/tests/fixtures/phpunit/testcasenames_unexpected_ns.php
- moodle/tests/phpunit_testcasenames_test.php
- tests/behat/ui.feature
- tests/local_codechecker_testcase.php
Sniff in charge of verifying various things related with PHPUnit
test cases names (files and classes and namespaces). Like:
- Error: _test.php files missing any valid test case.
- Error: incorrectly names test cases (not ended with _test[case]
- Warning: test case classes not matching test case file names.
- Error: found duplicate test case names.
- Error: found test case name proposed for another test case.
- Error: test case namespace not matching expected component namespace.
- Warning: test case namespace missing, suggesting a correct one.
- Error: found duplicate proposed test case names.
- Error: found proposed test case name existing for another test case.
Practically covered with unit tests. And behat tests updated.
Also included, small modification to local_codechecker_testcase …
> New moodle.PHPUnit.TestCaseNames Sniff

- moodle/Util/MoodleUtil.php
- moodle/tests/moodleutil_test.php
We need codechecker to continue working with PHP 7.0, because
it's used by moodle-plugin-ci that supports that version.
Hence, we have to downgrade code till it's decided to raise
requirements in both products.
Not much problem, only a few code recently introduced
(using some optional return type hinting that was added
with PHP 7.1) needs to be downgraded.
> Downgrade code to be PHP 7.0 compliant.

- moodle/Sniffs/PHPUnit/TestCaseNamesSniff.php
- moodle/tests/fixtures/phpunit/testcasenames_nomatch.php.fixed
Not much to say, while looking for various different approaches towards getting a bunch of test cases moved to the new policy (see [MDL-71049](https://tracker.moodle.org/browse/MDL-71049) ) I came with this tiny change, so now those class names can be auto-fixed.
Note this doesn't add the namespace or other bits, only the class name, the remaining problems will continue being reported.
> Make the fixer able to fix testcase name to match file name

- moodle/Sniffs/PHPUnit/TestCaseNamesSniff.php
- moodle/tests/fixtures/phpunit/testcasenames_correct_level2ns.php
- moodle/tests/fixtures/phpunit/testcasenames_unexpected_level2ns.php
- moodle/tests/phpunit_testcasenames_test.php
- tests/behat/ui.feature
Added one more check to the unit tests naming sniff that now
verify, for testcase classes, that they are in the expected
subdirectory, following the general namespace rules for stuff
under the "classes" directory.
Note that we still aren't checking the correctness under "classes"
and, once that's implemented, surely some code here will be moved
to the general namespaces sniff (a note about that has been added
to code).
Also, note that we aren't still checking for level2 correctness, that
must be a valid API or "local", whenever that's possible it will be
checked.
So, this only validates that the location (sub-directories) of the
file matches the sub-namespaces of the class.
Covered with tests.
> Verify that sub namespaces in test match the expected location

- moodle/ruleset.xml
- moodle/tests/fixtures/generic_classes_openingclassbrace.php
- moodle/tests/moodlestandard_test.php
- tests/behat/ui.feature
This implmements validation of use of curly braces in class declaration.
Fixes #168
> Use Generic.Classes.OpeningBraceSameLine sniff

- classes/privacy/provider.php
- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/tests/files_moodleinternal_test.php
- renderer.php
When the new detection was planned at #152, it was agreed
to make it a warning, not an error.
Instead, I missed that completely and implemented it as error.
So, this simple PR just downgrades the check to warning, as
originally planned.
With this patch applied, this will be the behavior:
- Only files having side effects (changing global state) do *require* (error) the MOODLE_INTERNAL check to be added.
- Files without side effects but having multiple artifacts (classes, interfaces and traits) "recommend" (warn) the MOODLE_INTERNAL check to be added.
- Any other file without side effects "recommend" (warn) the MOODLE_INTERNAL check to be removed.
That behavior matches the agreement @ https://tracker.moodle.org/browse/MDLSITE-5967 plus add the new/remaining warning about unexpected …
> Downgrade to warning the new MoodleInternalNotNeeded error

- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/tests/fixtures/files/moodleinternal/namespace_with_use_ok.php
No matter that comma-separated use statements are a violation of
the coding style (see Namespaces section), they, for sure, don't
constitute a side-effect at all, so the MOODLE_INTERNAL check
should be immune to them.
This fix just enables comma-separated to be properly processed,
covered with tests.
Fixes #175
> Avoid comma-separated use statements to require MOODLE_INTERNAL

- index.php
- lang/en/local_codechecker.php
- locallib.php
- renderer.php
- tests/behat/ui.feature
This is tiny UI improvement to optionally (not checked by default) show the coding standard cause the issue (which will be appended to the message):
> Optionaly output PHPCS standard that caused the problem in UI

- moodle/Sniffs/PHPUnit/TestCaseCoversSniff.php
- moodle/tests/fixtures/phpunit/testcasecovers_contradiction.php
- moodle/tests/fixtures/phpunit/testcasecovers_correct.php
- moodle/tests/fixtures/phpunit/testcasecovers_covers.php
- moodle/tests/fixtures/phpunit/testcasecovers_coversdefaultclass.php
- moodle/tests/fixtures/phpunit/testcasecovers_coversnothing.php
- moodle/tests/fixtures/phpunit/testcasecovers_missing.php
- moodle/tests/fixtures/phpunit/testcasecovers_mixed.php
- moodle/tests/fixtures/phpunit/testcasecovers_redundant.php
- moodle/tests/fixtures/phpunit/testcasecovers_skipped.php
- moodle/tests/moodlestandard_test.php
- moodle/tests/phpunit_testcasecovers_test.php
- tests/behat/ui.feature
This new feature will be in charge of validating the presence and
correctness of PHPUnit coverage annotations/tags.
Restrictions:
- It's only applied to Moodle 4.0 and up.
- It's only applied to files under /tests directories.
- It's only applied to files named `_test.php`.
- It's only applied to classes named `_test` or `_testcase`.
- it's only applied to methods named `test_ `.
Warnings implemented:
- Warn if both `@covers` and `@coversNothing` information are missing.
- Warn when there are contradictory mixed `@coversNothing` (at class) and
`@covers` (at method) combinations.
- Warn about redundant `@coversNothing` present both at class and method.
Errors implemented:
- Error when there are contradictory `@coversNothing` and `@covers` in the
same class or method.
- Error if the …
> Add new TestCaseCovers sniff to control @covers tags in unit tests

- moodle/Sniffs/Commenting/InlineCommentSniff.php
- moodle/Sniffs/Files/BoilerplateCommentSniff.php
- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/Sniffs/Files/RequireLoginSniff.php
- moodle/Sniffs/PHP/DeprecatedFunctionsSniff.php
- moodle/Sniffs/PHP/ForbiddenFunctionsSniff.php
- moodle/Sniffs/PHPUnit/TestCaseCoversSniff.php
- moodle/Sniffs/PHPUnit/TestCaseNamesSniff.php
- moodle/tests/fixtures/moodle_comenting_inlinecomment.php
- moodle/tests/moodlestandard_test.php
- moodle/tests/moodleutil_test.php
While playing with code coverage, there are some exceptional
places that are not reachable from PHPUnit. So, it's legit to
use the @codeCoverageIgnore annotations, that can be put
both in phpdoc blocks and in inline comments.
This commits enables the later (inline). For phpdoc block we'll
have to enable them in local_moodlecheck.
Covered with tests.
Recommended to look to the commits separately. The 1st one is implementing the feature (allow @codeCoverageIgnore annotations). And the 2nd just is applying it to codechecker own code.
> Allow codecoverageignore

- moodle/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- moodle/tests/fixtures/namingconventions/validfunctionname_correct.php
- moodle/tests/fixtures/namingconventions/validfunctionname_global.php
- moodle/tests/fixtures/namingconventions/validfunctionname_lower.php
- moodle/tests/fixtures/namingconventions/validfunctionname_scoped.php
- moodle/tests/namingconventions_validfunctionname_test.php
- tests/behat/ui.feature
Previously it was only being applied to classes and interfaces,
now also to traits and anon classes (and anything else that can
come in the future).
Covered with tests.
> Apply the ValidFunctionName to all scoped tokens

- moodle/Util/MoodleUtil.php
In order to use the core_component functions, sensible defaults are
required.
These sensible defaults are available, but the check of `$CFG->dirroot`
when $CFG is empty lead to a php warning, causing phpcs failures.
Even if this error is fixed, the default values in $CFG are then set to
NULL after including core_component, which means that uses of it work
with null values and cause require errors.
Fixes #184
> Apply sensible default values for $CFG if not specified

- .gitignore
- README.md
- composer.json
- moodle/Util/MoodleUtil.php
I wanted to use this more easily with phpcs.
I've gone for a global version of phpcs, rather than our packaged one, and I've included a dependency to automatically install it in the phpcs configuration.
To use:
```
composer global require moodlehq/moodle-local_codechecker
```
This will automatically install all requirements, and configure our codechecker in the list of phpcs paths.
You can also specify the Moodle standard as the default.
```
phpcs --config-set default_standard moodle
```
I've further extended this in my own repository to set certain opinionated "Best Practices": https://packagist.org/packages/andrewnicols/moodlebestpractice
> Add installation via Composer for phpcs rulesets

- moodle/ruleset.xml
- moodle/tests/fixtures/squiz_arrays_arraybracketspacing.php
- moodle/tests/fixtures/squiz_arrays_arraybracketspacing.php.fixed
- moodle/tests/squiz_arrays_arraybracketspacing_test.php
- tests/behat/ui.feature
Note this doesn't perform any check over arrays syntax,
only array indexes. Covered with tests.
Fixes #189
> Control no spacing in array index square brackets

- moodle/Sniffs/Files/MoodleInternalSniff.php
- moodle/ruleset.xml
- moodle/tests/files_moodleinternal_test.php
- moodle/tests/fixtures/files/moodleinternal/no_relevant_ok.php
- moodle/tests/fixtures/squiz_arrays_arraybracketspacing.php
- moodle/tests/fixtures/squiz_arrays_arraybracketspacing.php.fixed
- moodle/tests/squiz_arrays_arraybracketspacing_test.php
- tests/behat/ui.feature
Files containing exclusively non-relevant code are ok
As far as all the non-relevant code (namespace, uses, declare and
defines) is also code without side effects, these files don't need
the MOODLE_INTERNAL check).
Covered with tests.
This needs to be merged after #190.
Fixes #188
> No relevant files

- .github/workflows/ci.yml
Once the new 10.6.7 and 10.7.3 docker images are available
we can unpin MariaDB in all our repos.
Note the images are not yet available (as of Feb 25 2022), but I
wanted to verify one little thing with the current versions.
Fixes #150
> Unpin MariaDB

- README.md
GitHub has dropped support for unencrypted protocol (the git:// prefix).
> Fix the GitHub repository access protocol

- README.md
- locallib.php
Just spotted this while debugging something else. Hopefully this is a useful change.
> Update links to the coding style docs to the new dev docs

- phpcs.xml
Some problems are happening with core's phpcs.xml configuration, because it points to the "moodle" standard and that, as directory, doesn't exist anymore in codechecker (it's an alias now).
But it's an alias that only works under unix environments, now windows.
So we are adding our own phpcs.xml file, pointing to the correct standard. That will, automatically, stop phpcs to continue looking upwards.
See #207 for more detailed information about why core phpcs.xml is interfering in local_codechecker and, specifically, breaking under windows.
Fixes #207
> Shortcut core's .phpcs.xml by adding our own one

- .github/workflows/ci.yml
Related to this deprecation of NodeJS 12 for GHA actions:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
While it doesn't affect to this repository, let's bump to the new v3 version now so we keep it updated.
> Bump to actions/checkout@v3

- .github/workflows/ci.yml
This is part of the php81 epic:
https://tracker.moodle.org/browse/MDL-73016
It's near completed and passing in CIs, so let's enable the php81 tests for both MOODLE_401_STABLE and master (4.2dev).
Also, let's use moodle-plugin-ci 4 (dev-master) for php81 runs (to demo how people can keep v3 and v4 working together).
Ciao :-)
> Enable php81 tests for 401_STABLE and master (4.2dev)

- moodle
- phpcs.xml
- thirdpartylibs.xml
After one year since we moved the moodle coding style from local_codechecker to moodle-cs, it's time to perform this small cleanup that was kept to allow old integrations with local_codechecker to continue working.
Now, everybody should be already using moodle-cs, so we can remove those remaining bit:
- moodle dir alias.
- phpcs.xml file, needed to shortcut core's one.
- entry from thirdpartylibs.xml to avoid the moodle dir (alias) to be checked.
Fixes #202.
> Remove the "moodle" alias after 1 year
